import Head from "next/head";
import HomePage from "./home/page";

export default function Home() {

  return (
<div>
      <Head>
        <title>Gillian Palmer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" type="image/jpg" href="../public/web6.png"/>
      </Head>
      <main >
        <section className="min-h-screen">
          <HomePage />
        </section>
      </main>
      </div>
  );
}
